### PR TITLE
Use Swift 5.4 for Windows job on GitHub Actions

### PR DESCRIPTION
**Pull request by MaxDesiatov**
I've updated the Windows job on GitHub Actions to use a release build of Swift 5.4, and also updated the dependency in `Package.swift` and `Package.resolved`.

Additionally, all GitHub Actions triggers were updated to prevent jobs from running twice on pull requests created from branches in the same repositories.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@googlebot I signed it!

**Comment by MaxDesiatov** [comment]
@compnerd would you have a moment to have a look?

File: .github/workflows/tests_mac.yaml [hunk 1]
```diff
@@ -1,5 +1,10 @@
 name: tests-macos
-on: [push, pull_request]
+on:
+  push:
+    branches: [main]
+  pull_request:
+    branches: "*"
```
Comment (compnerd) [inline .github/workflows/tests_mac.yaml]: This shouldn't be needed
```suggestion
  pull_request:
```

File: .github/workflows/tests_ubuntu.yaml [hunk 2]
```diff
@@ -1,5 +1,10 @@
 name: tests-ubuntu
-on: [push, pull_request]
+on:
+  push:
+    branches: [main]
+  pull_request:
+    branches: "*"
```
Comment (compnerd) [inline .github/workflows/tests_ubuntu.yaml]:
```suggestion
  pull_request:
```

File: .github/workflows/tests_windows.yaml [hunk 3]
```diff
@@ -1,15 +1,20 @@
 name: tests-windows
-on: [push, pull_request]
+on:
+  push:
+    branches: [main]
+  pull_request:
+    branches: "*"
```
Comment (compnerd) [inline .github/workflows/tests_windows.yaml]:
```suggestion
  pull_request:
```

File: Package.swift [hunk 4]
```diff
@@ -24,7 +24,7 @@ let package = Package(
             targets: ["Benchmark"])
     ],
     dependencies: [
-        .package(url: "https://github.com/apple/swift-argument-parser", from: "0.0.1"),
+        .package(url: "https://github.com/apple/swift-argument-parser", from: "0.4.4"),
```
Comment (compnerd) [inline Package.swift]: Can you split this out into a separate change please?

Comment (MaxDesiatov) [reply Package.swift]: It looked like old version of SAP could fail to build with Swift 5.4 on Windows for some reason. But I've reverted the update in `Package.swift` and `Package.resolved` for now as you've requested. Curious to see if CI passes on Windows without updating the SAP dependency. Could you approve it for another CI run? I'm not able to trigger it with a sole push.

**Comment by compnerd** [comment]
Ah, I wonder if its the MSVCRT -> CRT renaming that you are referring to.  I think that we could just do something like:
```swift
#if os(Windows)
#if canImport(CRT)
import CRT
#else
import MSVCRT
#endif
#endif
```

**Comment by MaxDesiatov** [comment]
As far as I understand, this was fixed in the latest version of SAP, the current locked version fails to build on Windows with these kind of errors:

```
swift-argument-parser\Sources\ArgumentParser\Usage\HelpGenerator.swift:299:13: error: cannot find type 'CONSOLE_SCREEN_BUFFER_INFO' in scope
```

Would you like me to bring back the SAP update to this PR to fix that?

**Comment by MaxDesiatov** [comment]
I've confirmed in my fork https://github.com/MaxDesiatov/swift-benchmark/pull/2 that it won't build with the old snapshot currently used in this repository.
I've created a separate PR on this repo for SAP update, just in case. But that will fail too, as it did in my fork. https://github.com/google/swift-benchmark/pull/90

So I think that SAP update and CI update to Swift 5.4 should be included in this same PR for CI to be all green, unless I'm missing something?

**Comment by compnerd** [comment]
It can be made to work - s-a-p uses `canImport` to import `CRT` without the fallback for `MSVCRT` and that changed in the 5.4 release.  I suppose that its not worth the effort to split out the changes, but in general, it is preferable to stage the versions before bumping the release IMO.

**Comment by MaxDesiatov** [comment]
> it is preferable to stage the versions before bumping the release IMO.

I totally agree, but I'm still a bit confused as to how to land these two changes in separate PRs and to keep their respective CI status green at the same time. For now I'm bringing back the update to s-a-p version, but keeping it as a separate commit. That would preserve the separation after merge if you don't squash it. Ready for review and a CI run.

**Comment by compnerd** [comment]
I was thinking that we could inject a `CRT` module that just does `@_exported import MSVCRT`.  But again, I'm not too happy with that either.  Sorry for the churn here.  I think that the original idea of just bumping it together is fine.

**Review by compnerd — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
Thanks! Would it be possible to tag a new version so that other libraries targeting Windows could depend on that instead of the `main` branch?

**Comment by MaxDesiatov** [comment]
@regexident I see you've tagged the previous release, would you be able to tag a new one with this change included?

**Comment by regexident** [comment]
@MaxDesiatov I did? On mobile right now so can't check, but I doubt it since I'm just a random contributor like you. 😄

**Comment by MaxDesiatov** [comment]
Well, this is weird...

Screenshot 2021-09-18 at 14 54 44

**Comment by compnerd** [comment]
@MaxDesiatov I've tagged 0.1.1; I didn't see a reason for any thing bigger in terms of a version bump, the only change was for newer Swift releases on WIndows.

**Comment by MaxDesiatov** [comment]
Fantastic, thanks! 0.1.1 works perfectly fine for this 👍

**Comment by regexident** [comment]
Oh, interesting. I stand corrected then. 😅
